(SELECT NAME,(
    SELECT GRADE
    FROM GRADES
    WHERE MARKS BETWEEN Min_Mark AND Max_Mark
) AS GRADES , MARKS
FROM STUDENTS
WHERE MARKS > 70
 ORDER BY (
    SELECT GRADE
    FROM GRADES
    WHERE MARKS BETWEEN Min_Mark AND Max_Mark
) DESC, NAME ASC);
 
(
    SELECT NULL AS NAME, (
    SELECT GRADE
    FROM GRADES
    WHERE MARKS BETWEEN Min_Mark AND Max_Mark
) AS GRADES, MARKS
    FROM STUDENTS
    WHERE MARKS <= 70
    ORDER BY (
    SELECT GRADE
    FROM GRADES
    WHERE MARKS BETWEEN Min_Mark AND Max_Mark
) DESC, MARKS 
);
