SELECT COUNT(*) INTO @TOTAL FROM STATION ;
SET @N := 0;

SELECT ROUND(AVG(A.LAT_N), 4)
FROM (
    SELECT @N := @N + 1 AS ROW_ID, LAT_N
    FROM STATION
    ORDER BY LAT_N
) AS A
WHERE CASE WHEN MOD(@TOTAL, 2) = 0 
THEN A.ROW_ID IN (@TOTAL / 2, (@TOTAL / 2 + 1))
        ELSE A.ROW_ID = ((@TOTAL + 1) / 2)
    END;